---
- name: Create a directory if it does not exist
  local_action:
    module: file
    path: "{{ tmp_directory }}"
    state: directory

- name: keepalived stat
  local_action:
    module: stat
    path: "{{ tmp_directory }}/keepalived-{{ keepalived_version }}.tar.gz"
  register: st

- name: Download keepalived
  local_action:
    module: get_url
    url: "https://keepalived.org/software/keepalived-{{ keepalived_version }}.tar.gz"
    dest: "{{ tmp_directory }}/keepalived-{{ keepalived_version }}.tar.gz"
  when: st.stat.exists is false

- name: Copy files
  become: yes
  ansible.builtin.copy:
    src: "{{ tmp_directory }}/{{ item }}"
    dest: /tmp/{{ item }}
    owner: root
    group: root
    mode: '0755'
  with_items:
    - keepalived-{{ keepalived_version }}.tar.gz

- name: Install packages
  become: true
  ansible.builtin.package:
    name:
      - gcc-c++ 
      - openssl-devel 
      - pcre-static 
      - pcre-devel 
      - systemd-devel
    state: latest
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install packages
  become: true
  apt:
    pkg:
      - build-essential 
      - libssl-dev
    update_cache: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Keepalived stopped
  ansible.builtin.systemd:
    state: stopped
    name: keepalived
  ignore_errors: yes

- name: Unarchive haproxy-x.x.x.tar.gz
  ansible.builtin.unarchive:
    src: /tmp/keepalived-{{ keepalived_version }}.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Remove file
  become: yes
  ansible.builtin.file:
    path: /usr/local/bin/genhash
    state: absent

- name: Copy config files
  become: yes
  ansible.builtin.copy:
    src: "/etc/keepalived/{{ item }}"
    dest: "/etc/keepalived/{{ item }}.old"
    owner: root
    group: root
    remote_src: yes
  with_items:
    - keepalived.conf
  ignore_errors: yes
  
- name: Remove haproxy package
  ansible.builtin.package:
    name:
      - keepalived
    state: absent
  ignore_errors: yes

- name: Build keepalived configure
  command: ./configure
  args:
    chdir: /tmp/keepalived-{{ keepalived_version }}

- name: Build haproxy 'all' target with extra arguments
  make:
    chdir: /tmp/keepalived-{{ keepalived_version }}
    target: all

- name: Build haproxy 'install' target with extra arguments
  become: true
  make:
    chdir: /tmp/keepalived-{{ keepalived_version }}
    target: install
  ignore_errors: yes

- name: Copy config files
  become: yes
  ansible.builtin.copy:
    src: "/etc/keepalived/{{ item }}.old"
    dest: "/etc/keepalived/{{ item }}"
    owner: root
    group: root
    remote_src: yes
  with_items:
    - keepalived.conf
  ignore_errors: yes

- name: Keepalived reload and restarted
  become: yes
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: keepalived

- name: Delete install files/folders
  file:
    path: "/tmp/{{ item }}"
    state: absent
  with_items:
    - keepalived-{{ keepalived_version }}
    - keepalived-{{ keepalived_version }}.tar.gz